// Code generated by MockGen. DO NOT EDIT.
// Source: clients/render/render.go

// Package mock_render is a generated GoMock package.
package mock_render

import (
	gomock "github.com/golang/mock/gomock"
	io "io"
	reflect "reflect"
)

// MockRender is a mock of Render interface
type MockRender struct {
	ctrl     *gomock.Controller
	recorder *MockRenderMockRecorder
}

// MockRenderMockRecorder is the mock recorder for MockRender
type MockRenderMockRecorder struct {
	mock *MockRender
}

// NewMockRender creates a new mock instance
func NewMockRender(ctrl *gomock.Controller) *MockRender {
	mock := &MockRender{ctrl: ctrl}
	mock.recorder = &MockRenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRender) EXPECT() *MockRenderMockRecorder {
	return m.recorder
}

// JSON mocks base method
func (m *MockRender) JSON(w io.Writer, status int, v interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "JSON", w, status, v)
}

// JSON indicates an expected call of JSON
func (mr *MockRenderMockRecorder) JSON(w, status, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JSON", reflect.TypeOf((*MockRender)(nil).JSON), w, status, v)
}
